In [1]:
import pandas as pd

In [70]:
data = pd.read_json(r"E:\CancerDetection-project\DataSets\mutations.2021-12-24.json")
data1 = pd.read_json(r"E:\CancerDetection-project\DataSets\tcga file for MCV.json")
data2 = pd.read_excel(r"E:\CancerDetection-project\DataSets\VIS-MCV (1).xlsx")

In [72]:
data.head(-1)

,consequence,mutation_subtype,ssm_id,genomic_dna_change
0,[{'transcript': {'annotation': {'polyphen_impa...,Single base substitution,5c93b065-f994-5890-b9e3-919013f09806,chr6:g.35291619C>A
1,[{'transcript': {'annotation': {'polyphen_impa...,Single base substitution,0b48eadd-9e9d-501c-abc0-29084cd692ba,chr4:g.55904482C>A
2,[{'transcript': {'annotation': {'polyphen_impa...,Single base substitution,95ffd99c-a8f9-5bde-8e4b-64e1bef5af30,chr3:g.121282281G>A
3,[{'transcript': {'annotation': {'polyphen_impa...,Single base substitution,978c7864-92d9-526d-891c-a9e213d6d80c,chr1:g.155688330G>T
4,[{'transcript': {'annotation': {'polyphen_impa...,Single base substitution,c4cef95f-a48b-5631-9eed-c13b272aed06,chrX:g.41346402G>A
...,...,...,...,...
846,[{'transcript': {'annotation': {'polyphen_impa...,Single base substitution,b13a006d-446a-5cd3-b832-67fbe60d8bf1,chr11:g.14358803C>G
847,[{'transcript': {'annotation': {'polyphen_impa...,Single base substitution,315767cb-47c3-5fb5-b626-ddd43b86b5f0,chr9:g.128345464C>A
848,[{'transcript': {'annotation': {'polyphen_impa...,Single base substitution,ff2ed5be-1449-57bb-acc8-5791f4eebfae,chr22:g.41877299T>C
849,[{'transcript': {'annotation': {'polyphen_impa...,Single base substitution,2d7b721c-56da-53ce-b04d-6338278011c1,chr2:g.159977298C>A
850,[{'transcript': {'annotation': {'polyphen_impa...,Single base substitution,8ce15658-8fa8-5e1a-ad1c-1ea6e03d4cd4,chr9:g.72930988C>T

In [78]:
for i in data["genomic_dna_change"]:
    print(i.split(':')[1].split('.')[1][:-3])

35291619
55904482
121282281
155688330
41346402
31667977
155029269
12770999
98863293
9891073
215397773
16150350
67163912
132256977
146195181
29440811
67175118
48507886
70981411
11590569
207143915
136496425_136496426in
135672827
62518778
4179732
54542768
134784386
71659020
63555913
4994432
45947246
226366071
43161489
102733609
207165562
93668929
141427703
128070423
19381109
70539975
118975282
82028037
57726080
44355980
48553664
142412619
46379469
151792063
39105619
114096077
134885316
78601711_78601712insGGA
38848355
2989756
17837197
32396368_32396369insGC
39492880
155014161
7778850
55518134
176177071
51964911
234309294
26030524
29066893
111238822
156935536
61880124
51704819
152323109_152323110insGGA
141341099
96327612
18337479
41216552_41216553ins
111598987
235172702delTTTCTTGAA
6430592
54819870
15428425
87873854
132146655
31258476
56032639
101032686
125026739
15245988
81502773
143977770
138442094
46651532
98995714
100089054
202859081
55715144
100820189
7932991
12920347
154811632
43534100
49668535
78774696
130885257
22567888
17835160
51467830
83285857
110471592
132257848
64576542
148217378
2488838
56882819
117835547
101365036
99052258
58477166
34904745
4183824
163503363
1218449
140786742
114674739
32435605
63497322
46694033
62034996
29310996
51027581
8426660
39322950
145823819
39588064
94440081_94440085delinsGT
94765711
79366665
167248282
136503269_136503270in
81498020
99330430
7745089
32396367_32396368insCGCC
112450406
33417660
48384300
2057224
178986828
20199825
37020675
96945827
73486801
59199687
93672373
77193588
141383709
80708578
113608170
218072491
15724422
122115679
154360308
45436237
117330708
55940101
5961903
167249817
112450361
240682586
15112529
9408519
40565738
169596612
82548722
82322897
151463501
6676359
196319079
219421364
76611572
32396365_32396366insGGACC
53109706
30430377
39411407
33083575
210590816
231262396
195780940
115524599
74371711
152647823
56074297
70882905
203483409
80090335
93870785
8684077
99613047
130028814
48171107
47751202
14808091
36626853
71941614
159841221
29112333
24818549_24818550i
189695018
15161180
148335601
9827215
215900778
50464483
73807867
101025981
62736647
105029696
21760567
128063576
177276312
107597395
71498529
35046489
80157762
68884658
16371668
44987534
57727398
99955640
171392154
150521625
82965947
38495881
12718419
135486661
87094583
148814982
132484375
90972961
76736329_76736330insG
51411336
138197572
10478678
706508
54941081
195779589
173890494
32396398_32396398in
70038627
2818286
153679827
134566404
139019926
156873636
145849693
88734517
15627443
145996168
144667750
43508014
113697292
2403588
80353354
78013262
121080884
125759694
134579070
6112140
67936459
95381697
147189758
80837991
32417641
4796285
15958214
2270840
46132522
16933075
184135408
2020074
67071456
88860122
135486019
114582611
62371322
32396401_32396401in
41475611
19523974
85280464
131520348
155275790
60444715
119852853
34834593_34834594insC
73442505
30987356
34859495
44608602
128483919
80076946
40936534
99105457
63198702
50379111
123452777
1953508
17168818
212954
198085847
119310771
6849698
13138361
22138481
103927093
48560892
66548505
64153630de
30373990
72196799
79968106
218434674
40243903
18854635
40879927
54055162
113838105
47057053
53275637
49134485d
8141816
119030103
109541498
121147141
31611221
64686591
16829746
27246221
43015225
7406771
167063735
32396371_32396374insTCCTAAAA
59192045
202695997
57473699
124038590
78160257
6778804
38815559
118739279
167246481
141209825
228293515
24676649
132257868
41347002
41936007_41936008i
50167250
116443740
47017215
52657191
66544865
74866463
64894741
54791044
109287484
56401369
6461532
152220146
30736357d
73354137
6197724_6197725i
155217353
75236953
6090369
17750233
17275351
64097876
144520419
179971053
128128850
228158281
143400202
83873124
70282468
59679687
40462714
18978501
51271171
32434587_32434588i
102010329
100290691
142208972_142208973i
153662461
46920445
144058807
43678130
155853329
7985060
38260188
13334416
54960325
54028678
102749627
3564340
2917856
6010241
136115157
87957915
70214482
50352775
38938939
148807695
31553140
51474342
119930160
57197340
22125603
135095903
25607415
9186704
6354555
139373792
44115684
15618286
78492814
130384722
11080567
28018504
34319574
57191398
60935877
21229411
49476970
38383755
92476159
106714664delGTGGGTTTTCACACTGTGTCTCTC
101547185
141383623
24057752
61913410
141345644
35109428
3767731_3767732i
25218578
10812315
35139291
20001898
151373582delT
134377666
32396378_32396379in
56617304
114312307
45689526
53593435
39052004
116436043
50359128
126165641
50840251
42753198
7024267
3730452
84469179
45175742
1966875
10996303
62546336
42910536
34131290
170998359
142034799
6627010
71655429
9766142
56355362
4286103
149546014
56804321
153070651
50576612
79292294
33064858
67036738_67036739i
10301538
124446896
122592547
11839290
15075710
35997871
170983427
13610571
48633064
33185995
12496543
186614254
32450997
129739720
114716127
25709938
50353139
152672544del
94149225
106627249_106627250ins
46773730
35090246
13322170
79850009
161517998
180075194
209775734
50352460
31698500
737612
9179906
44865003
75507096
106506994_106506998insGGGGG
33443865
140426079
413349
201053572
37015168
50561575
99287905_99287906in
130013957_130013958i
180318861
103135760
5501089
32573359
153777556
58880449
28256493
51139370
101540267
81696425
10514341
36293514
71279944_71279945ins
90241491
75619698
37182943
21859403
34834595_34834596in
13866085
62000283
3745352_3745353insCC
70266261
103312154
171309776
51959925
87366327
3025962
45346613
46303633
146591838
31327690
154199833
68121657
37009733
67718731
35434423
48498715
97873957
98908929
46412040
31538971
62597537
15942191_15942192i
31094427
119918030
28796137_28796138insG
66402968
47795268
141179313
72605560
62003161
129136482
193255724
114713908
26184256
117810959
55480817
103005222
55518130
79614052
212791545
49151276
18329217
46813484
56883629
89900774
59639065
14941858
157135500
49664446
54942839
104832755
16068139
968090
195759144
1882656
67304557
184386612
99445867
7677705
9356446
32337966
57451052
96366006
64753960
195783765
202952599
38281545
47144260
71570703
23379742
47835996
240093483
32392704_32392705insT
35330472
159446847
112243884
26463354
131011829
114716126
19380149
136504898
94160001
9854299
150471363
151167135
143808996
17977695
229635258
1974938
133587935
50109981
23743177
1232940
9854298
30011556
247723611
83310823
59961028
45407080
151139392
83523836
186306369
65089068
204123788
179765736
37826284
72213207
61813846
21651421
159193890
35951922
32396400_32396401i
52358337
43032372
114716127
19177266
35669648
17395032
122808175
86511129
53156616
103689874
1271350
130154342
43273344
617964
94536098
232136587_232136588insCC
21373994
118339134
31860035delC
50518153
2001596
107395318
25592949
140857735
24223099
40577298
110892307
15946023
6968687
206479881
67269689
127330992
76855624
22376439
33301475_33301476ins
131520350de
114716123
57570471
84117137
112450395
58709857
178551202
111926067
100276494
28320863
147758524
11241923
7910366
50162990
172339163
106129539_106129540ins
11362606
77353874
58993640
62910319
31688321
21487924
61421145
21324447
44541264_44541265i
73769981
81941174
70622610
32417642
14135532
41159140
35620260
155183959
102656787
77039830
142203192
73434900
7249576
67180188
100155304
50707603
44212004
145872712
178593226
136361045
40074321
84721457del
49026905
124648177
59596765
10544766
10683702
57356095
65505225
177351391
26924053
49809420
144882775
122261798
150232370
167833145
88433075
43534853
33566237
130159865
96158782
38347664_38347665insCT
222521863
7054836
128945911
143960177
110889627
140869226
42193522
137555437
3678995
151582142
105226161
32396396_32396397in
40380829
38481277
76896012
44002536
6461533
67398245
47649021
53059925
63285607
119051608
10759776
83051788
130425865
30561956
54463307_54463308i
136336956
115604708
37068837
79001924
70062564
88448627
25227351
57470669
49026756
129531172
37009549
17838299
89868683
37537487
26961982
154122425
55807115
25769128
93451143
142753865
889646
59514398
135905264
54575894
134417235del
677813
50464428
73807173
34122518
110579316
124413567
30929428
110137154
49022947
41909473
75029451_75029452i
184054852
208443504
150410976_150410977insAGCCCC
41467186
11839291
33331449
27796217
32396281_32396281insTGA
178837392
49206542
65109727
45729746
51705427
13344249
89953951
132241001
37282207
69035480
2232522
1243310
113174470
205072567
12204398
169674312
100949923
14358803
128345464
41877299
159977298
72930988
68971921

In [75]:
data2.head(-1)

,Virus Name,Chromosome,Begin Location,End Location,Target gene,Unnamed: 5
0,MCV,chr8,65568962,65566806.0,NaN,chr8:65568962-65566806
1,MCV,chr8,65568962,65566806.0,NaN,chr8:65568962-65566806
2,MCV,chr9,121417276,NaN,NaN,chr9:121417276-121417276
3,MCV,chr6,19684666,19684859.0,NaN,chr6:19684666-19684859
4,MCV,chr5,2282589,NaN,NaN,chr5:2282589-2282589
5,MCV,chr3,61561985,NaN,PTPRG,chr3:61561985-61561985
6,MCV,chr6,9842760,NaN,OFCC1,chr6:9842760-9842760
7,MCV,chr3,88824524,NaN,NaN,chr3:88824524-88824524
8,MCV,chr10,36041150,NaN,NaN,chr10:36041150-36041150
9,MCV,chr1,31904698,NaN,PTP4A2,chr1:31904698-31904698
10,MCV,chr1,31940936,31941056.0,PTP4A2,chr1:31940936-31941056
11,MCV,chr6,20758430,NaN,NaN,chr6:20758430-20758430
12,MCV,chr20,32132694,NaN,CBFA2T2,chr20:32132694-32132694
13,MCV,chr3,182180601,NaN,LINC01994,chr3:182180601-182180601
14,MCV,chr19,39307703,NaN,ECH1,chr19:39307703-39307703
15,MCV,chr19,39307378,NaN,ECH1,chr19:39307378-39307378
16,MCV,chr6,20635170,NaN,CDKAL1,chr6:20635170-20635170
17,MCV,chr2,197433173,NaN,SF3B1,chr2:197433173-197433173
18,MCV,chr1,10790267,NaN,CASZ1,chr1:10790267-10790267
19,MCV,chr12,69690384,NaN,BEST3,chr12:69690384-69690384
20,MCV,chr11,25063435,NaN,LUZP2,chr11:25063435-25063435
21,MCV,chr3,181965770,NaN,NaN,chr3:181965770-181965770

In [80]:
data2_fixed = []
for count,val in enumerate(data2["End Location"]):
    if (pd.isna(val)):
        data2_fixed.append(data2["Begin Location"][count])
    else:
        data2_fixed.append(int(val))
print(data2_fixed)

[65566806, 65566806, 121417276, 19684859, 2282589, 61561985, 9842760, 88824524, 36041150, 31904698, 31941056, 20758430, 32132694, 182180601, 39307703, 39307378, 20635170, 197433173, 10790267, 69690384, 25063435, 181965770, 181965781]

In [74]:
data1.head(-1)

,summary,primary_site,project,submitter_id,demographic
0,"{'file_count': 1, 'data_categories': [{'file_c...",Skin,{'project_id': 'GENIE-MDA'},GENIE-MDA-2341,{'gender': 'male'}
1,"{'file_count': 3, 'data_categories': [{'file_c...",Skin,{'project_id': 'GENIE-MSK'},GENIE-MSK-P-0005180,{'gender': 'male'}
2,"{'file_count': 2, 'data_categories': [{'file_c...",Skin,{'project_id': 'GENIE-DFCI'},GENIE-DFCI-000717,{'gender': 'female'}
3,"{'file_count': 2, 'data_categories': [{'file_c...",Skin,{'project_id': 'GENIE-MSK'},GENIE-MSK-P-0019490,{'gender': 'female'}
4,"{'file_count': 1, 'data_categories': [{'file_c...",Skin,{'project_id': 'GENIE-MDA'},GENIE-MDA-2166,{'gender': 'female'}
...,...,...,...,...,...
2873,"{'file_count': 2, 'data_categories': [{'file_c...",Skin,{'project_id': 'GENIE-MSK'},GENIE-MSK-P-0018466,{'gender': 'male'}
2874,"{'file_count': 5, 'data_categories': [{'file_c...",Skin,{'project_id': 'FM-AD'},AD17858,{'gender': 'male'}
2875,"{'file_count': 5, 'data_categories': [{'file_c...",Skin,{'project_id': 'FM-AD'},AD6191,{'gender': 'female'}
2876,"{'file_count': 2, 'data_categories': [{'file_c...",Skin,{'project_id': 'GENIE-MSK'},GENIE-MSK-P-0012455,{'gender': 'male'}
2877,"{'file_count': 5, 'data_categories': [{'file_c...",Skin,{'project_id': 'FM-AD'},AD1201,{'gender': 'female'}